### ISSUE TITLE
fmri data can be 3D too :)

### ISSUE THREAD

**Issue by dohmatob** [neurospin/pypreprocess#122]
______________________________________________________niigz2nii - 0.0s, 0.0min
Traceback (most recent call last):
  File "pypreprocess.py", line 23, in <module>
    subjects = do_subjects_preproc(sys.argv[1])
  File "/home/jb232823/CODE/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 1667, in do_subjects_preproc
    subject_data, **preproc_params) for subject_data in subjects)
  File "/usr/lib/python2.7/dist-packages/joblib/parallel.py", line 653, in __call__
    self.dispatch(function, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/joblib/parallel.py", line 400, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/joblib/parallel.py", line 138, in __init__
    self.results = func(*args, **kwargs)
  File "/home/jb232823/CODE/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 1195, in do_subject_preproc
    subject_data.sanitize(deleteorient=deleteorient, niigz2nii=True)
  File "/home/jb232823/CODE/pypreprocess/pypreprocess/subject_data.py", line 396, in sanitize
    self._check_func_names_and_shapes()
  File "/home/jb232823/CODE/pypreprocess/pypreprocess/subject_data.py", line 289, in _check_func_names_and_shapes
    self.func[sess1]))
RuntimeError: Functional images for session number 1 doesn't constitute a 4D film; the shape of the session is (175, 256, 170); the images for this session are /neurospin/lnao/Pdiff/josselin/jennifer_roi/normalise_mni/pypreprocess_output/001/t2_t1.nii

**Comment by dohmatob** [comment]
Also, as pointed out by @mrahim, PET data is most 3D.

**Comment by dohmatob** [comment]
Fixed.
