### ISSUE TITLE
tsdiffana not working on 3D images

### ISSUE THREAD

**Issue by dohmatob** [neurospin/pypreprocess#124]
[Memory] Calling pypreprocess.time_diff.multi_session_time_slice_diffs...
multi_session_time_slice_diffs([ '/neurospin/lnao/Pdiff/josselin/jennifer_roi/normalise_mni/pypreprocess_output/001/wt2_t1.nii'])
Traceback (most recent call last):
File "pypreprocess.py", line 23, in 
subjects = do_subjects_preproc(sys.argv[1])
File "/home/jb232823/CODE/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 1667, in do_subjects_preproc
subject_data, *preproc_params) for subject_data in subjects)
File "/usr/lib/python2.7/dist-packages/joblib/parallel.py", line 653, in call
self.dispatch(function, args, kwargs)
File "/usr/lib/python2.7/dist-packages/joblib/parallel.py", line 400, in dispatch
job = ImmediateApply(func, args, kwargs)
File "/usr/lib/python2.7/dist-packages/joblib/parallel.py", line 138, in init
self.results = func(args, *kwargs)
File "/home/jb232823/CODE/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 1341, in do_subject_preproc
subject_data.finalize_report(last_stage=last_stage)
File "/home/jb232823/CODE/pypreprocess/pypreprocess/subject_data.py", line 577, in finalize_report
results_gallery=self.results_gallery)
File "/home/jb232823/CODE/pypreprocess/pypreprocess/reporting/preproc_reporter.py", line 726, in generate_tsdiffana_thumbnail
results = qa_mem.cache(multi_session_time_slice_diffs)(image_files)
File "/home/jb232823/CODE/pypreprocess/pypreprocess/external/joblib/memory.py", line 170, in call
out = self.call(args, *kwargs)
File "/home/jb232823/CODE/pypreprocess/pypreprocess/external/joblib/memory.py", line 334, in call
output = self.func(args, **kwargs)
File "/home/jb232823/CODE/pypreprocess/pypreprocess/time_diff.py", line 41, in multi_session_time_slice_diffs
results_ = time_slice_diffs(img)
Not quite there ye...

File "/home/jb232823/CODE/pypreprocess/pypreprocess/time_diff.py", line 112, in time_slice_diffs
img = check_niimg_4d(img)
File "/home/jb232823/.local/lib/python2.7/site-packages/nilearn/_utils/niimg_conversions.py", line 288, in check_niimg_4d
dtype=dtype)
File "/home/jb232823/.local/lib/python2.7/site-packages/nilearn/_utils/niimg_conversions.py", line 211, in check_niimg
raise DimensionError(len(niimg.shape), ensure_ndim)
nilearn._utils.exceptions.DimensionError: Data must be a 4D Niimg-like object but you provided a 3D image. See http://nilearn.github.io/building_blocks/manipulating_mr_images.html#niimg.

**Comment by bthirion** [comment]
I don't get it : chec_niimg_4d accepts iterables, i.e. list of 3D images.
Of course, you cannot launch it on a single 3D image.
I am afraid I don't get the point.

**Comment by dohmatob** [comment]
Yep, this is 'technically' not a problem with tsdiffana. Fixed anyways. Closing.
