### ISSUE TITLE
SPM12 support (was NewSegment Inputs Error in NYU Example)

### ISSUE THREAD

**Issue by mrahim** [neurospin/pypreprocess#125]
When running `nipype_preproc_spm_nyu.py`, I've got this error :
```
Traceback (most recent call last):
  File "nipype_preproc_spm_nyu.py", line 27, in <module>
    results = do_subjects_preproc(jobfile, dataset_dir=dataset_dir)
  File "/home/mr243268/.local/lib/python2.7/site-packages/pypreprocess/nipype_preproc_spm_utils.py", line 1779, in do_subjects_preproc
    **preproc_params)
  File "/home/mr243268/.local/lib/python2.7/site-packages/pypreprocess/nipype_preproc_spm_utils.py", line 1487, in _do_subjects_dartel
    ignore_exception=False
  File "/home/mr243268/.local/lib/python2.7/site-packages/nipype/caching/memory.py", line 69, in __call__
    interface.inputs.set(**kwargs)
  File "/home/mr243268/anaconda/lib/python2.7/site-packages/traits/has_traits.py", line 1771, in trait_set
    setattr( self, name, value )
  File "/home/mr243268/anaconda/lib/python2.7/site-packages/traits/trait_types.py", line 2190, in validate
    return TraitListObject( self, object, name, value )
  File "/home/mr243268/anaconda/lib/python2.7/site-packages/traits/trait_handlers.py", line 2430, in __init__
    raise excp
traits.trait_errors.TraitError: Each element of the 'tissues' trait of a NewSegmentInputSpec instance must be a tuple of the form: (a tuple of the form: (an existing file name, an integer), an integer, a tuple of the form: (a boolean, a boolean), a tuple of the form: (a boolean, a boolean)), but a value of (('/usr/local/src/spm12/spm12_mcr/spm12/toolbox/Seg/TPM.nii', 1), 2, (True, True), (False, False)) <type 'tuple'> was specified.
```

**Comment by dohmatob** [comment]
OK, broken example.

**Comment by dohmatob** [comment]
This is strange. I can't reproduce it. What is your SPM version ? What is your nipype version ? Is your nipype installed as explained in the Readme ?

**Comment by mrahim** [comment]
spm12 standalone, nipype 0.10
I just realized that it was an old version of pypreprocess, now I've updated and the script is running.
I'll tell you if everything is ok.

**Comment by mrahim** [comment]
Different example, (almost) same issue.
May be related to spm12 ?

in `nipype_preproc_spm_multimodal_faces.py`
```
Traceback (most recent call last):
  File "nipype_preproc_spm_multimodal_faces.py", line 50, in <module>
    segment=True, normalize=True)
  File "/home/mr243268/dev/modules/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 1296, in do_subject_preproc
    hardlink_output=hardlink_output)
  File "/home/mr243268/dev/modules/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 602, in _do_subject_segment
    ignore_exception=False
  File "/home/mr243268/.local/lib/python2.7/site-packages/nipype/caching/memory.py", line 69, in __call__
    interface.inputs.set(**kwargs)
  File "/home/mr243268/anaconda/lib/python2.7/site-packages/traits/has_traits.py", line 1771, in trait_set
    setattr( self, name, value )
  File "/home/mr243268/anaconda/lib/python2.7/site-packages/traits/trait_types.py", line 2190, in validate
    return TraitListObject( self, object, name, value )
  File "/home/mr243268/anaconda/lib/python2.7/site-packages/traits/trait_handlers.py", line 2430, in __init__
    raise excp
traits.trait_errors.TraitError: Each element of the 'tissue_prob_maps' trait of a SegmentInputSpec instance must be an existing file name, but a value of '/usr/local/src/spm12/spm12_mcr/spm12/tpm/grey.nii' <type 'str'> was specified.
```

**Comment by dohmatob** [comment]
On Tue, Aug 4, 2015 at 5:21 PM, mrahim <notifications@github.com> wrote:

> Different example, (almost) same issue.
> May be related to spm12 ?
>
Yes I'd say the problem is that we don't yet support spm12. I'm opening an
issue to track SPM12 compat asap.

>
>
in nipype_preproc_spm_multimodal_faces.py
>
> Traceback (most recent call last):
>   File "nipype_preproc_spm_multimodal_faces.py", line 50, in <module>
>     segment=True, normalize=True)
>   File "/home/mr243268/dev/modules/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 1296, in do_subject_preproc
>     hardlink_output=hardlink_output)
>   File "/home/mr243268/dev/modules/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 602, in _do_subject_segment
>     ignore_exception=False
>   File "/home/mr243268/.local/lib/python2.7/site-packages/nipype/caching/memory.py", line 69, in __call__
>     interface.inputs.set(**kwargs)
>   File "/home/mr243268/anaconda/lib/python2.7/site-packages/traits/has_traits.py", line 1771, in trait_set
>     setattr( self, name, value )
>   File "/home/mr243268/anaconda/lib/python2.7/site-packages/traits/trait_types.py", line 2190, in validate
>     return TraitListObject( self, object, name, value )
>   File "/home/mr243268/anaconda/lib/python2.7/site-packages/traits/trait_handlers.py", line 2430, in __init__
>     raise excp
> traits.trait_errors.TraitError: Each element of the 'tissue_prob_maps' trait of a SegmentInputSpec instance must be an existing file name, but a value of '/usr/local/src/spm12/spm12_mcr/spm12/tpm/grey.nii' <type 'str'> was specified.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neurospin/pypreprocess/issues/125#issuecomment-127647350>
> .
>



-- 
DED

**Comment by dohmatob** [comment]
OK, no need for a new issue. Let's just keep this one for tracking the SPM12 compat.

**Comment by mrahim** [comment]
Now I'm getting this message 

```
Traceback (most recent call last):
  File "nipype_preproc_spm_auditory.py", line 47, in <module>
    subject_data = do_subjects_preproc(jobfile, dataset_dir=dataset_dir)[0]
  File "/home/mr243268/dev/modules/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 1686, in do_subjects_preproc
    subject_data, **preproc_params) for subject_data in subjects)
  File "/home/mr243268/.local/lib/python2.7/site-packages/joblib/parallel.py", line 653, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/mr243268/.local/lib/python2.7/site-packages/joblib/parallel.py", line 400, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/mr243268/.local/lib/python2.7/site-packages/joblib/parallel.py", line 138, in __init__
    self.results = func(*args, **kwargs)
  File "/home/mr243268/dev/modules/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 1374, in do_subject_preproc
    subject_data.finalize_report(last_stage=last_stage)
  File "/home/mr243268/dev/modules/pypreprocess/pypreprocess/subject_data.py", line 579, in finalize_report
    results_gallery=self.results_gallery)
  File "/home/mr243268/dev/modules/pypreprocess/pypreprocess/reporting/preproc_reporter.py", line 737, in generate_tsdiffana_thumbnail
    axes = plot_tsdiffs(results, use_same_figure=False)
  File "/home/mr243268/dev/modules/pypreprocess/pypreprocess/time_diff.py", line 178, in plot_tsdiffs
    T = len(results['volume_means'])
TypeError: object of type 'NDArrayWrapper' has no len()
```

**Comment by mrahim** [comment]
Sorry, I cleaned the cache directory and re-launched the examples under SPM12 and SPM8, both are working.
