### ISSUE TITLE
Segment Inputs Error in Haxby Example

### ISSUE THREAD

**Issue by mrahim** [neurospin/pypreprocess#126]
Another broken example, might be due to the spm version (12) ?
```
Traceback (most recent call last):
  File "nipype_preproc_spm_haxby.py", line 77, in <module>
    dataset_description=DATASET_DESCRIPTION,
  File "/home/mr243268/.local/lib/python2.7/site-packages/pypreprocess/nipype_preproc_spm_utils.py", line 1771, in do_subjects_preproc
    subject_data, **preproc_params) for subject_data in subjects)
  File "/home/mr243268/.local/lib/python2.7/site-packages/joblib/parallel.py", line 653, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/mr243268/.local/lib/python2.7/site-packages/joblib/parallel.py", line 400, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/mr243268/.local/lib/python2.7/site-packages/joblib/parallel.py", line 138, in __init__
    self.results = func(*args, **kwargs)
  File "/home/mr243268/.local/lib/python2.7/site-packages/pypreprocess/nipype_preproc_spm_utils.py", line 1378, in do_subject_preproc
    hardlink_output=hardlink_output
  File "/home/mr243268/.local/lib/python2.7/site-packages/pypreprocess/nipype_preproc_spm_utils.py", line 648, in _do_subject_segment
    ignore_exception=False
  File "/home/mr243268/.local/lib/python2.7/site-packages/nipype/caching/memory.py", line 69, in __call__
    interface.inputs.set(**kwargs)
  File "/home/mr243268/anaconda/lib/python2.7/site-packages/traits/has_traits.py", line 1771, in trait_set
    setattr( self, name, value )
  File "/home/mr243268/anaconda/lib/python2.7/site-packages/traits/trait_types.py", line 2190, in validate
    return TraitListObject( self, object, name, value )
  File "/home/mr243268/anaconda/lib/python2.7/site-packages/traits/trait_handlers.py", line 2430, in __init__
    raise excp
traits.trait_errors.TraitError: Each element of the 'tissue_prob_maps' trait of a SegmentInputSpec instance must be an existing file name, but a value of '/usr/local/src/spm12/spm12_mcr/spm12/tpm/grey.nii' <type 'str'> was specified.
```

**Comment by dohmatob** [comment]
This will be fixed by PR #139.
