### ISSUE TITLE
IndexError: list index out of range in nipy/nipy/labs/viz_tools/coord_tools.py

### ISSUE THREAD

**Issue by dohmatob** [neurospin/pypreprocess#13]
This is triggered when preprocessing openfmri. I am intensionally not giving any details to reproduce this.

[Memory] Calling check_preprocessing.plot_cv_tc...
plot_cv_tc('/vaporific/edohmato/pypreprocess_runs/openfmri/ds107/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-Normalize/0373e12bc04f5e6fde8be91db678bcb3/wrbold.nii', 
'task001_run001', 'sub001', '/vaporific/edohmato/pypreprocess_runs/openfmri/ds107/sub001', cv_tc_plot_outfile='/vaporific/edohmato/pypreprocess_runs/openfmri/ds107/sub001/cv_tc_after.png', plot_diff=True)
[Memory]    0.0s, 0.0min: Loading nibabel.funcs.concat_images...
_______________________________________concat_images cache loaded - 0.1s, 0.0min
________________________________________________________________________________
[Memory] Calling nibabel.loadsave.save...
save(<nibabel.nifti1.Nifti1Image object at 0x526e550>, '/vaporific/edohmato/pypreprocess_runs/openfmri/ds107/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-Normalize/0373e12bc04f5e6fde8be91db678bcb3/fourD_func.nii')
_____________________________________________________________save - 0.0s, 0.0min
[Memory]    0.0s, 0.0min: Loading check_preprocessing.compute_cv...
__________________________________________compute_cv cache loaded - 0.0s, 0.0min
Traceback (most recent call last):
  File "nipype_preproc_spm_openfmri_ds107.py", line 149, in <module>
    results = main(DATA_DIR, OUTPUT_DIR)
  File "nipype_preproc_spm_openfmri_ds107.py", line 124, in main
    report_filename=report_filename
  File "/home/edohmato/CODE/FORKED/pypreprocess/nipype_preproc_spm_utils.py", line 1369, in do_group_preproc
    subject_data, **kwargs) for subject_data in subjects)
  File "/home/edohmato/CODE/FORKED/pypreprocess/src/joblib/joblib/parallel.py", line 513, in __call__
    self.dispatch(function, args, kwargs)
  File "/home/edohmato/CODE/FORKED/pypreprocess/src/joblib/joblib/parallel.py", line 321, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "/home/edohmato/CODE/FORKED/pypreprocess/src/joblib/joblib/parallel.py", line 145, in __init__
    self.results = func(*args, **kwargs)
  File "/home/edohmato/CODE/FORKED/pypreprocess/nipype_preproc_spm_utils.py", line 1068, in do_subject_preproc
    plot_diff=True)
  File "/home/edohmato/CODE/FORKED/pypreprocess/src/joblib/joblib/memory.py", line 163, in __call__
    return self.call(*args, **kwargs)
  File "/home/edohmato/CODE/FORKED/pypreprocess/src/joblib/joblib/memory.py", line 316, in call
    output = self.func(*args, **kwargs)
  File "/home/edohmato/CODE/FORKED/pypreprocess/check_preprocessing.py", line 173, in plot_cv_tc
    title=title,
  File "/home/edohmato/CODE/FORKED/pypreprocess/src/nipy/nipy/labs/viz_tools/activation_maps.py", line 220, in plot_map
    slicer.plot_map(map, affine, **kwargs)
  File "/home/edohmato/CODE/FORKED/pypreprocess/src/nipy/nipy/labs/viz_tools/slicers.py", line 343, in plot_map
    self._map_show(map, affine, type='imshow', **kwargs)
  File "/home/edohmato/CODE/FORKED/pypreprocess/src/nipy/nipy/labs/viz_tools/slicers.py", line 374, in _map_show
    get_mask_bounds(not_mask, affine)
  File "/home/edohmato/CODE/FORKED/pypreprocess/src/nipy/nipy/labs/viz_tools/coord_tools.py", line 134, in get_mask_bounds
    x_slice, y_slice, z_slice = ndimage.find_objects(mask)[0]
IndexError: list index out of range

**Comment by bthirion** [comment]
See #76
