### ISSUE TITLE
dataset_dir issue in Auditory example

### ISSUE THREAD

**Issue by mrahim** [neurospin/pypreprocess#160]
Here is the error
```
Traceback (most recent call last):
  File "nipype_preproc_spm_auditory.py", line 44, in <module>
    subject_data = do_subjects_preproc(jobfile, dataset_dir=dataset_dir)[0]
  File "/home/mr243268/dev/modules/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 1529, in do_subjects_preproc
    "dataset_dir", None))
  File "/home/mr243268/dev/modules/pypreprocess/pypreprocess/conf_parser.py", line 123, in _generate_preproc_pipeline
    options = _parse_job(config_file, **kwargs)
  File "/home/mr243268/dev/modules/pypreprocess/pypreprocess/conf_parser.py", line 98, in _parse_job
    cobj.walk(_sanitize, call_on_sections=True, **replacements)
  File "/home/mr243268/anaconda/lib/python2.7/site-packages/configobj.py", line 923, in walk
    **keywargs)
  File "/home/mr243268/anaconda/lib/python2.7/site-packages/configobj.py", line 894, in walk
    val = function(self, entry, **keywargs)
  File "/home/mr243268/dev/modules/pypreprocess/pypreprocess/conf_parser.py", line 90, in _sanitize
    exec cmd
  File "<string>", line 1, in <module>
AttributeError: 'Bunch' object has no attribute 'data_dir'
```

The error comes from this value in the `.ini` file 
```
dataset_dir = "pycmd: from pypreprocess.datasets import fetch_spm_auditory; print fetch_spm_auditory().data_dir"
```

**Comment by dohmatob** [comment]
Fixed. @mrahim can you confirm and close ?

**Comment by mrahim** [comment]
Yes, fixed.
