### ISSUE TITLE
Pure python pipeline example is broken

### ISSUE THREAD

**Issue by mrahim** [neurospin/pypreprocess#175]
Although we don't use often pure python functions, the code should be refactored.
We should also take into account nilearn's check_niimg functions.

**Comment by AlexandreAbraham** [comment]
This one seems doable to me, plus there is "nilearn" in the description.

**Comment by KamalakerDadi** [comment]
@mehdi this is what you are pointing at ?
Traceback (most recent call last):
  File "pure_python_preproc_demo.py", line 16, in <module>
    tsdiffana=True, realign=True, report=True, reslice=True)
  File "/home/kamalakar/Kamalakar/work/pypreprocess/pypreprocess/purepython_preproc_utils.py", line 281, in do_subject_preproc
   ``` n_sessions = len(subject_data.session_ids)```
```TypeError: object of type 'NoneType' has no len()```
