### ISSUE TITLE
Pandas should be added to requirements

### ISSUE THREAD

**Issue by arthurmensch** [neurospin/pypreprocess#194]
```
python nipype_preproc_spm_auditory.py
```

```
from pypreprocess.datasets import fetch_spm_auditory
/opt/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/__init__.py:1312: UserWarning:  This call to matplotlib│from pypreprocess.reporting.glm_reporter import generate_subject_stats_report
.use() has no effect                                                                                                  │import pandas as pd
because the backend has already been chosen;                                                                          │from pypreprocess.external.nistats.design_matrix import (make_design_matrix,
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,                                                    │                                                         check_design_matrix,
or matplotlib.backends is imported for the first time.                                                                │                                                         plot_design_matrix)
                                                                                                                      │from pypreprocess.external.nistats.glm import FMRILinearModel
  warnings.warn(_use_error_msg)                                                                                       │
/opt/anaconda/envs/py27/lib/python2.7/site-packages/pypreprocess/configure_spm.py:143: UserWarning: Failed to configur│# file containing configuration for preprocessing the data
e SPM!                                                                                                                │jobfile = os.path.join("spm_auditory_preproc.ini")
  warnings.warn('Failed to configure SPM!')                                                                           │
Traceback (most recent call last):                                                                                    │# fetch spm auditory data
  File "nipype_preproc_spm_auditory.py", line 14, in <module>                                                         │sd = fetch_spm_auditory()
    from pypreprocess.reporting.glm_reporter import generate_subject_stats_report                                     │dataset_dir = os.path.dirname(os.path.dirname(os.path.dirname(sd.anat)))
  File "/opt/anaconda/envs/py27/lib/python2.7/site-packages/pypreprocess/reporting/glm_reporter.py", line 8, in <modul│
e>                                                                                                                    │# construct experimental paradigm
    from pypreprocess.external.nistats.design_matrix import plot_design_matrix                                        │stats_start_time = time.ctime()
  File "/opt/anaconda/envs/py27/lib/python2.7/site-packages/pypreprocess/external/nistats/design_matrix.py", line 35, │tr = 7.
in <module>                                                                                                           │n_scans = 96
    from pandas import DataFrame                                                                                      │_duration = 6
ImportError: No module named pandas
```

**Comment by bthirion** [comment]
Could you take care of this ?
Thx !
