### ISSUE TITLE
local variable 'linked_filename' referenced before assignment

### ISSUE THREAD

**Issue by chrplr** [neurospin/pypreprocess#268]
```python
2017-01-17 14:58:51,094:INFO: setting SPM MCR path to "/i2bm/local/bin/spm12" and "use_mcr" to True
2017-01-17 14:58:51,094:INFO: SPM configuration succeeded using SPM MCR.
170117-14:58:51,138 workflow INFO:
	 Executing node 34b7af8fe64661b0ca2dfe1b9a54725d in dir: /home/cp983411/epi-example-dicom/essai/nifti/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/34b7af8fe64661b0ca2dfe1b9a54725d
170117-15:00:17,162 workflow INFO:
	 Runtime memory and threads stats unavailable
	Hardlinked /home/cp983411/epi-example-dicom/nifti/StudyID-001_SeriesNumber-000009_000001ap080059.nii -> /home/cp983411/epi-example-dicom/essai/nifti/StudyID-001_SeriesNumber-000009_000001ap080059.nii ...
/home/cp983411/.local/lib/python2.7/site-packages/pypreprocess/nipype_preproc_spm_utils.py:420: UserWarning: subject_data.anat=None (empty); skipping coregistration!
  subject_data.anat))
Traceback (most recent call last):
  File "preproc.py", line 23, in <module>
    subjects = do_subjects_preproc(sys.argv[1])
  File "/home/cp983411/.local/lib/python2.7/site-packages/pypreprocess/nipype_preproc_spm_utils.py", line 1718, in do_subjects_preproc
    subject_data, **preproc_params) for subject_data in subjects)
  File "/volatile/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/volatile/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/volatile/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/volatile/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/volatile/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/cp983411/.local/lib/python2.7/site-packages/pypreprocess/nipype_preproc_spm_utils.py", line 1377, in do_subject_preproc
    subject_data.hardlink_output_files(final=True)
  File "/home/cp983411/.local/lib/python2.7/site-packages/pypreprocess/subject_data.py", line 451, in hardlink_output_files
    setattr(self, item, linked_filename)
UnboundLocalError: local variable 'linked_filename' referenced before assignment
```

**Comment by chrplr** [comment]
Solved by the PR "corrected indentation bug that provoked UnboundLocalError"
