### ISSUE TITLE
Error running an examples/easy_start/nipype_preproc_spm_auditory.py with Nipype >=0.13

### ISSUE THREAD

**Issue by KamalakerDadi** [neurospin/pypreprocess#288]
```python
2018-01-26 15:09:46,326:INFO: found SPM directory to be "/home/kamalakar/opt/spm8/spm8/spm8_mcr/spm8"
2018-01-26 15:09:46,326:INFO: using SPM version: 8
2018-01-26 15:09:46,326:INFO: setting SPM MCR path to "/home/kamalakar/opt/spm8/spm8.sh" and "use_mcr" to True
2018-01-26 15:09:46,326:INFO: SPM configuration succeeded using SPM MCR.
Traceback (most recent call last):
  File "examples/easy_start/nipype_preproc_spm_auditory.py", line 52, in <module>
    subject_data = do_subjects_preproc(jobfile, dataset_dir=dataset_dir)[0]
  File "/home/kamalakar/Kamalakar/work/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 1715, in do_subjects_preproc
    subject_data, **preproc_params) for subject_data in subjects)
  File "/home/kamalakar/miniconda2/envs/pypreprocess/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/kamalakar/miniconda2/envs/pypreprocess/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/kamalakar/miniconda2/envs/pypreprocess/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/kamalakar/miniconda2/envs/pypreprocess/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/home/kamalakar/miniconda2/envs/pypreprocess/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/home/kamalakar/miniconda2/envs/pypreprocess/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/kamalakar/Kamalakar/work/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 1298, in do_subject_preproc
    software=realign_software
  File "/home/kamalakar/Kamalakar/work/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 319, in _do_subject_realign
    jobtype=jobtype, **kwargs)
  File "/home/kamalakar/miniconda2/envs/pypreprocess/lib/python2.7/site-packages/nipype/caching/memory.py", line 74, in __call__
    interface.inputs.trait_set(**kwargs)
  File "/home/kamalakar/.local/lib/python2.7/site-packages/traits/has_traits.py", line 1544, in trait_set
    setattr( self, name, value )
  File "/home/kamalakar/miniconda2/envs/pypreprocess/lib/python2.7/site-packages/nipype/interfaces/base/traits_extension.py", line 335, in validate
    value = super(MultiPath, self).validate(object, name, newvalue)
  File "/home/kamalakar/.local/lib/python2.7/site-packages/traits/trait_types.py", line 2337, in validate
    return TraitListObject( self, object, name, value )
  File "/home/kamalakar/.local/lib/python2.7/site-packages/traits/trait_handlers.py", line 2313, in __init__
    raise excp
traits.trait_errors.TraitError: Each element of the 'in_files' trait of a RealignInputSpec instance must be an existing file name, but a value of [u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_004.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_005.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_006.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_007.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_008.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_009.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_010.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_011.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_012.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_013.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_014.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_015.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_016.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_017.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_018.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_019.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_020.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_021.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_022.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_023.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_024.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_025.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_026.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_027.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_028.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_029.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_030.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_031.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_032.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_033.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_034.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_035.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_036.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_037.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_038.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_039.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_040.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_041.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_042.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_043.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_044.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_045.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_046.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_047.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_048.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_049.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_050.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_051.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_052.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_053.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_054.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_055.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_056.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_057.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_058.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_059.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_060.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_061.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_062.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_063.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_064.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_065.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_066.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_067.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_068.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_069.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_070.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_071.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_072.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_073.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_074.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_075.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_076.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_077.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_078.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_079.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_080.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_081.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_082.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_083.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_084.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_085.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_086.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_087.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_088.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_089.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_090.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_091.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_092.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_093.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_094.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_095.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_096.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_097.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_098.img', u'/home/kamalakar/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/0f1bac640d9cea8dadaf57a6dfdcdc0c/afM00223_099.img'] <type 'list'> was specified.
```

I am currently experiencing problem running this example with more recent versions of Nipype. I can open an issue there to ask.

Meanwhile, please let me know if you know why ?

**Comment by KamalakerDadi** [comment]
FYI Issue is here https://github.com/nipy/nipype/issues/2406

**Comment by KamalakerDadi** [comment]
For now, I think we can add a small note in readme document to be cautious of running examples with more recent Nipype versions.

I will issue a PR.

**Comment by dohmatob** [comment]
Ok, thanks for looking into this.
