### ISSUE TITLE
Multiple issue in the pure_python examples

### ISSUE THREAD

**Issue by CherkaouiHamza** [neurospin/pypreprocess#298]
`python2 coreg_demos.py` or
`python3 coreg_demos.py`
'crash' because the SVD do not converge. 

`python2 pure_python_preproc_demo.py` or
`python3 pure_python_preproc_demo.py`

'crash' because of 
`Traceback (most recent call last):
  File "pure_python_preproc_demo.py", line 16, in <module>
    tsdiffana=True, realign=True, report=True, reslice=True)
  File "/home/hcherkaoui/src/THESE/pypreprocess/pypreprocess/purepython_preproc_utils.py", line 282, in do_subject_preproc
    n_sessions = len(subject_data.session_ids)
TypeError: object of type 'NoneType' has no len()`

in both case.

We should make all examples passed.

**Comment by CherkaouiHamza** [comment]
related to  #175
But could hide even more bugs...
