### ISSUE TITLE
nipype_preproc_spm_auditory.py  example broken (after the sprint) (?)

### ISSUE THREAD

**Issue by CherkaouiHamza** [neurospin/pypreprocess#302]
After a step-by-step installation that went well (no error, no warnings), launching the nipype_preproc_spm_auditory example result in:

(I have enable exception raising)

hc252523@is233976:~/src/THESE/pypreprocess/examples/easy_start$ python nipype_preproc_spm_auditory.py 
2018-02-21 11:44:06,467:INFO: found SPM directory to be "/home/hc252523/opt/spm12/spm12/spm12_mcr/spm12"
2018-02-21 11:44:06,467:INFO: using SPM version: 12
2018-02-21 11:44:06,467:INFO: setting SPM MCR path to "/home/hc252523/opt/spm12/spm12.sh" and "use_mcr" to True
2018-02-21 11:44:06,467:INFO: SPM configuration succeeded using SPM MCR.
2018-02-21 11:44:06,468:INFO: found SPM directory to be "/home/hc252523/opt/spm12/spm12/spm12_mcr/spm12"
2018-02-21 11:44:06,468:INFO: using SPM version: 12
2018-02-21 11:44:06,469:INFO: setting SPM MCR path to "/home/hc252523/opt/spm12/spm12.sh" and "use_mcr" to True
2018-02-21 11:44:06,469:INFO: SPM configuration succeeded using SPM MCR.
Using the following parameters for preprocessing:
	normalize=False
	coreg_anat_to_func=False
	slice_timing_software=spm
	output_modulated_tpms=True
	func_write_voxel_sizes=[3.0, 3.0, 3.0]
	anat_write_voxel_sizes=[1.0, 1.0, 1.0]
	dataset_description=<a href=http://www.fil.ion.ucl.ac.uk/spm/data/auditory/>SPM Auditory
 (single-subject)</a>

	smooth_software=spm
	realign_software=spm
	register_to_mean=True
	deleteorient=False
	dataset_dir=/home/hc252523/nilearn_data/spm_auditory
	report=True
	dataset_id=/home/hc252523/nilearn_data/spm_auditory
	realign_reslice=False
	segment=True
	interleaved=False
	coregister_software=spm
	anat_fwhm=0.0
	spm_dir=None
	dartel=False
	coregister_reslice=False
	fwhm=[5.0, 5.0, 5.0]
	newsegment=False
	TR=7.0
	realign=True
	coregister=True
	slice_order=ascending
	slice_timing=True
	caching=True
	tsdiffana=True
	matlab_exec=None
	TA=TR * (1 - 1 / nslices)
180221-11:44:06,642 root WARNING:
	 [MemorizedFunc(func=<function niigz2nii at 0x7fe34db04578>, cachedir='/home/hc252523/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/joblib')]: Computing func niigz2nii, argument hash 13206e50e35e7f35ab59f270135895b8 in directory /home/hc252523/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/joblib/pypreprocess/io_utils/niigz2nii/13206e50e35e7f35ab59f270135895b8
________________________________________________________________________________
[Memory] Calling pypreprocess.io_utils.niigz2nii...
niigz2nii([ '/home/hc252523/nilearn_data/spm_auditory/sub001/fM00223/fM00223_004.img',
  '/home/hc252523/nilearn_data/spm_auditory/sub001/fM00223/fM00223_005.img',
  '/home/hc252523/nilearn_data/spm_auditory/sub001/fM00223/fM00223_006.img',
  '/home/hc252523/nilearn_data/spm_auditory/sub001/fM00223/fM00223_007.img',
  '/home/hc252523/nilearn_data/spm_auditory/sub001/fM00223/fM00223_008.img',
  '/home/hc252523/nilearn_data/spm_auditory/sub001/fM00223/fM00223_009.img',
  '/home/hc252523/nilearn_data/spm_auditory/sub001/fM00223/fM00223_010.img',
  '/home/hc252523/nilearn_data/spm_auditory/sub001/fM00223/fM00223_011.img',
  '/home/hc252523/nilearn_data/spm_auditory/sub001/fM00223/fM00223_012.img',
  '/hom..., output_dir='/home/hc252523/nilearn_data/spm_auditory/pypreprocess_scratch/sub001')
Persisting in /home/hc252523/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/joblib/pypreprocess/io_utils/niigz2nii/13206e50e35e7f35ab59f270135895b8
________________________________________________________niigz2nii - 0.0s, 0.0min
180221-11:44:06,647 root WARNING:
	 [MemorizedFunc(func=<function niigz2nii at 0x7fe34db04578>, cachedir='/home/hc252523/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/joblib')]: Computing func niigz2nii, argument hash d0f2f65d1f5d42070553d3133aa0fc6b in directory /home/hc252523/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/joblib/pypreprocess/io_utils/niigz2nii/d0f2f65d1f5d42070553d3133aa0fc6b
________________________________________________________________________________
[Memory] Calling pypreprocess.io_utils.niigz2nii...
niigz2nii('/home/hc252523/nilearn_data/spm_auditory/sub001/sM00223/sM00223_002.img', output_dir='/home/hc252523/nilearn_data/spm_auditory/pypreprocess_scratch/sub001')
Persisting in /home/hc252523/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/joblib/pypreprocess/io_utils/niigz2nii/d0f2f65d1f5d42070553d3133aa0fc6b
________________________________________________________niigz2nii - 0.0s, 0.0min
2018-02-21 11:44:06,747:INFO: found SPM directory to be "/home/hc252523/opt/spm12/spm12/spm12_mcr/spm12"
2018-02-21 11:44:06,748:INFO: using SPM version: 12
2018-02-21 11:44:06,748:INFO: setting SPM MCR path to "/home/hc252523/opt/spm12/spm12.sh" and "use_mcr" to True
2018-02-21 11:44:06,748:INFO: SPM configuration succeeded using SPM MCR.
180221-11:44:06,755 workflow INFO:
	 Executing node 503c070fcecc899b3783c6a42a34542e in dir: /home/hc252523/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/503c070fcecc899b3783c6a42a34542e
Traceback (most recent call last):
  File "nipype_preproc_spm_auditory.py", line 49, in <module>
    subject_data = do_subjects_preproc(jobfile, dataset_dir=dataset_dir)[0]
  File "/home/hc252523/src/THESE/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 1715, in do_subjects_preproc
    subject_data, **preproc_params) for subject_data in subjects)
  File "/usr/lib/python2.7/dist-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/lib/python2.7/dist-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/lib/python2.7/dist-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/lib/python2.7/dist-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/usr/lib/python2.7/dist-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/usr/lib/python2.7/dist-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/hc252523/src/THESE/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 1280, in do_subject_preproc
    hardlink_output=hardlink_output
  File "/home/hc252523/src/THESE/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 199, in _do_subject_slice_timing
    ignore_exception=False #XXX
  File "/home/hc252523/.local/lib/python2.7/site-packages/nipype/caching/memory.py", line 86, in __call__
    out = node.run()
  File "/home/hc252523/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/home/hc252523/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/home/hc252523/.local/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/home/hc252523/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1034, in run
    runtime = self._run_wrapper(runtime)
  File "/home/hc252523/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 991, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/hc252523/.local/lib/python2.7/site-packages/nipype/interfaces/spm/base.py", line 311, in _run_interface
    results = self.mlab.run()
  File "/home/hc252523/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1034, in run
    runtime = self._run_wrapper(runtime)
  File "/home/hc252523/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1660, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/hc252523/.local/lib/python2.7/site-packages/nipype/interfaces/matlab.py", line 141, in _run_interface
    runtime = super(MatlabCommand, self)._run_interface(runtime)
  File "/home/hc252523/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1694, in _run_interface
    self.raise_exception(runtime)
  File "/home/hc252523/.local/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1618, in raise_exception
    raise RuntimeError(message)
RuntimeError: Command:
/home/hc252523/opt/spm12/spm12.sh run script /home/hc252523/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/503c070fcecc899b3783c6a42a34542e/pyscript_slicetiming.m
Standard output:
Warning: Unable to open display ':1'.  You will not be able to display graphics on the screen.
Warning: "Run" is deprecated: use "Batch". 
> In spm_standalone at 20
SPM12, version 7219 (standalone)
MATLAB, version 7.10.0.499 (R2010a)
 ___  ____  __  __                                            
/ __)(  _ \(  \/  )                                           
\__ \ )___/ )    (   Statistical Parametric Mapping           
(___/(__)  (_/\/\_)  SPM12 - http://www.fil.ion.ucl.ac.uk/spm/

Warning: Unknown extension: 'script' 
> In spm_jobman>load_jobs at 345
  In spm_jobman at 143
  In spm_standalone at 101
Warning: No batch job found in 'script' 
> In spm_jobman>load_jobs at 354
  In spm_jobman at 143
  In spm_standalone at 101
Execution failed: script
Bye for now...

Error using ==> spm_jobman at 246
No valid job.
Error in spm_jobman (line 246)
Error in spm_standalone (line 101)

Standard error:

Return code: 1
Interface MatlabCommand failed to run. 
Interface SliceTiming failed to run.

**Comment by mrahim** [comment]
It looks like you are using the matlab spm rather than the standalone spm.

Le 21 févr. 2018 11:46 AM, "CherkaouiHamza" <notifications@github.com> a
écrit :

**Comment by CherkaouiHamza** [comment]
I don't have matlab on this laptop... How can I check your intuition?
If that's the case, any idea how I've done that? I've just followed the instruction in the README.rst

**Comment by mrahim** [comment]
Ok, I just saw `MATLAB, version 7.10.0.499 (R2010a)`
I was suspecting a matlab shipped with your (cea) ubuntu distribution.
Then, we should check what changes we made to the slicetiming.

**Comment by CherkaouiHamza** [comment]
So far I understand:
nipype run 
```
/home/hc252523/opt/spm12/spm12.sh run script /home/hc252523/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/503c070fcecc899b3783c6a42a34542e/pyscript_slicetiming.m
```
(see previous traceback)

And `spm12.sh` parse the command line that way: **spm12.sh [action] [args (here the script file)]**.

For an unknow reason there is this "script" keyword that make the parsing failed...

I'll try to understand who inject this  "script" keyword.

**Comment by CherkaouiHamza** [comment]
I was not able the understand at which point in the code from pyprepreprocess to nipype who set the command line to be `spm12.sh run script`, so in `/home/hc252523/opt/spm12/spm12.sh` I change the line:
```
exec "${SPM12_STANDALONE_HOME}/run_spm12.sh" "${SPM12_STANDALONE_HOME}/../mcr/v713" ${1+"$@"}
```
to
```
exec "${SPM12_STANDALONE_HOME}/run_spm12.sh" "${SPM12_STANDALONE_HOME}/../mcr/v713" batch ${3}
```
Which fix the crash, but It stills produced failed co-registration:

![](https://i.imgur.com/0I1FvOc.png)

So there is another issue here... First of all, I need to be sure that's a reproducible issue (and not just on my machine...).

Can someone runs (it will change  your local installation of your pypreprocess):

```
# downloading
wget https://github.com/neurospin/pypreprocess/archive/master.zip;
unzip master.zip;
cd pypreprocess-master/
#installing
. continuous_integration/install_spm12.sh
cd -
wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh
pip install scipy nose nibabel scikit-learn nipype pandas matplotlib nilearn configobj --user
python setup.py install --user
# running the example
cd examples/easy_start/
python nipype_preproc_spm_auditory.py
```

And posts here the traceback?

**Comment by CherkaouiHamza** [comment]
This issue was reproduced in three different computers (include Kamalakar's one)
@chrplr have you check this problem regarding #281 and #291

**Comment by chrplr** [comment]
Just tried on a clean install of anaconda2 and pypreprocess-master.
It does not crash (see below), but indeed the activation map and the backgound image are not corregistered.

I remarked that in the parameters list call: 
        normalize=False
	coreg_anat_to_func=False

So it is not supposed to performd any spatial normalization. Ok, but realign and segment are set to True, and pypreprocess does not seem to perform them (?)
 



cp983411@is153352:~/tmp/pypreprocess-master/examples/easy_start$ python nipype_preproc_spm_auditory.py 
/home/cp983411/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-02-26 13:04:15,237:INFO: found SPM directory to be "/home/cp983411/opt/spm12/spm12/spm12_mcr/spm12"
2018-02-26 13:04:15,237:INFO: using SPM version: 12
2018-02-26 13:04:15,237:INFO: setting SPM MCR path to "/home/cp983411/opt/spm12/spm12.sh" and "use_mcr" to True
2018-02-26 13:04:15,237:INFO: SPM configuration succeeded using SPM MCR.
2018-02-26 13:04:15,239:INFO: found SPM directory to be "/home/cp983411/opt/spm12/spm12/spm12_mcr/spm12"
2018-02-26 13:04:15,239:INFO: using SPM version: 12
2018-02-26 13:04:15,240:INFO: setting SPM MCR path to "/home/cp983411/opt/spm12/spm12.sh" and "use_mcr" to True
2018-02-26 13:04:15,240:INFO: SPM configuration succeeded using SPM MCR.
Using the following parameters for preprocessing:
	normalize=False
	coreg_anat_to_func=False
	slice_timing_software=spm
	output_modulated_tpms=True
	func_write_voxel_sizes=[3.0, 3.0, 3.0]
	anat_write_voxel_sizes=[1.0, 1.0, 1.0]
	dataset_description=<a href=http://www.fil.ion.ucl.ac.uk/spm/data/auditory/>SPM Auditory
 (single-subject)</a>

	smooth_software=spm
	realign_software=spm
	register_to_mean=True
	deleteorient=False
	dataset_dir=/home/cp983411/nilearn_data/spm_auditory
	report=True
	dataset_id=/home/cp983411/nilearn_data/spm_auditory
	realign_reslice=False
	segment=True
	interleaved=False
	coregister_software=spm
	anat_fwhm=0.0
	spm_dir=None
	dartel=False
	coregister_reslice=False
	fwhm=[5.0, 5.0, 5.0]
	newsegment=False
	TR=7.0
	realign=True
	coregister=True
	slice_order=ascending
	slice_timing=True
	caching=True
	tsdiffana=True
	matlab_exec=None
	TA=TR * (1 - 1 / nslices)
180226-13:04:15,438 root WARNING:
	 [MemorizedFunc(func=<function niigz2nii at 0x7f5e731fe1b8>, cachedir='/home/cp983411/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/joblib')]: Computing func niigz2nii, argument hash ddb0564788cfdf0507ada6266566ab40 in directory /home/cp983411/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/joblib/pypreprocess/io_utils/niigz2nii/ddb0564788cfdf0507ada6266566ab40
________________________________________________________________________________
[Memory] Calling pypreprocess.io_utils.niigz2nii...
niigz2nii([ '/home/cp983411/nilearn_data/spm_auditory/sub001/fM00223/fM00223_004.img',
  '/home/cp983411/nilearn_data/spm_auditory/sub001/fM00223/fM00223_005.img',
  '/home/cp983411/nilearn_data/spm_auditory/sub001/fM00223/fM00223_006.img',
  '/home/cp983411/nilearn_data/spm_auditory/sub001/fM00223/fM00223_007.img',
  '/home/cp983411/nilearn_data/spm_auditory/sub001/fM00223/fM00223_008.img',
  '/home/cp983411/nilearn_data/spm_auditory/sub001/fM00223/fM00223_009.img',
  '/home/cp983411/nilearn_data/spm_auditory/sub001/fM00223/fM00223_010.img',
  '/home/cp983411/nilearn_data/spm_auditory/sub001/fM00223/fM00223_011.img',
  '/home/cp983411/nilearn_data/spm_auditory/sub001/fM00223/fM00223_012.img',
  '/hom..., output_dir='/home/cp983411/nilearn_data/spm_auditory/pypreprocess_scratch/sub001')
Persisting in /home/cp983411/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/joblib/pypreprocess/io_utils/niigz2nii/ddb0564788cfdf0507ada6266566ab40
________________________________________________________niigz2nii - 0.0s, 0.0min
180226-13:04:15,447 root WARNING:
	 [MemorizedFunc(func=<function niigz2nii at 0x7f5e731fe1b8>, cachedir='/home/cp983411/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/joblib')]: Computing func niigz2nii, argument hash e26ff79300111f64267b725df611df52 in directory /home/cp983411/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/joblib/pypreprocess/io_utils/niigz2nii/e26ff79300111f64267b725df611df52
________________________________________________________________________________
[Memory] Calling pypreprocess.io_utils.niigz2nii...
niigz2nii('/home/cp983411/nilearn_data/spm_auditory/sub001/sM00223/sM00223_002.img', output_dir='/home/cp983411/nilearn_data/spm_auditory/pypreprocess_scratch/sub001')
Persisting in /home/cp983411/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/joblib/pypreprocess/io_utils/niigz2nii/e26ff79300111f64267b725df611df52
________________________________________________________niigz2nii - 0.0s, 0.0min
2018-02-26 13:04:15,584:INFO: found SPM directory to be "/home/cp983411/opt/spm12/spm12/spm12_mcr/spm12"
2018-02-26 13:04:15,584:INFO: using SPM version: 12
2018-02-26 13:04:15,584:INFO: setting SPM MCR path to "/home/cp983411/opt/spm12/spm12.sh" and "use_mcr" to True
2018-02-26 13:04:15,584:INFO: SPM configuration succeeded using SPM MCR.
/home/cp983411/anaconda2/lib/python2.7/site-packages/nipype/interfaces/base/specs.py:145: UserWarning: Input ignore_exception in interface SliceTiming is deprecated. Will be removed or raise an error as of release 1.0.0 
  warn(msg)
180226-13:04:15,605 workflow INFO:
	 [Node] Setting-up "45af9dc8a5df8314b76ce4bd5962e7a9" in "/home/cp983411/nilearn_data/spm_auditory/pypreprocess_scratch/sub001/cache_dir/nipype_mem/nipype-interfaces-spm-preprocess-SliceTiming/45af9dc8a5df8314b76ce4bd5962e7a9".
180226-13:04:15,656 workflow INFO:
	 [Node] Running "45af9dc8a5df8314b76ce4bd5962e7a9" ("nipype.interfaces.spm.preprocess.SliceTiming")
180226-13:04:21,123 workflow INFO:
	 [Node] Finished "45af9dc8a5df8314b76ce4bd5962e7a9".

Preproc report for subject sub001 written to /home/cp983411/nilearn_data/spm_auditory/pypreprocess_output/sub001/reports/report_preproc.html .

Finishing /home/cp983411/nilearn_data/spm_auditory/pypreprocess_output...

	HTML report written to /home/cp983411/nilearn_data/spm_auditory/pypreprocess_output/report_preproc.html

Fitting a GLM (this takes time) ..
Saving mask image /home/cp983411/nilearn_data/spm_auditory/pypreprocess_output/sub001/mask.nii.gz
Computing contrasts ..
	contrast id: active-rest
		z map: /home/cp983411/nilearn_data/spm_auditory/pypreprocess_output/sub001/z_maps/active-rest.nii.gz
		t map: /home/cp983411/nilearn_data/spm_auditory/pypreprocess_output/sub001/t_maps/active-rest.nii.gz
		effects map: /home/cp983411/nilearn_data/spm_auditory/pypreprocess_output/sub001/effects_maps/active-rest.nii.gz
		variance map: /home/cp983411/nilearn_data/spm_auditory/pypreprocess_output/sub001/variance_maps/active-rest.nii.gz

/home/cp983411/anaconda2/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:106: MatplotlibDeprecationWarning: The axisbg attribute was deprecated in version 2.0. Use facecolor instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
/home/cp983411/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py:896: MatplotlibDeprecationWarning: The set_axis_bgcolor function was deprecated in version 2.0. Use set_facecolor instead.
  return func(v)

Statistic report written to /home/cp983411/nilearn_data/spm_auditory/pypreprocess_output/sub001/reports/report_stats.html

**Comment by chrplr** [comment]
currently, in `spm_auditory_preproc.ini`

     disable_normalize = True

**Comment by chrplr** [comment]
Yet, setting

     disable_normalize = False

does not seem to change anything (that is, normalization is not performed)

**Comment by CherkaouiHamza** [comment]
in `pypreprocess//nipype_preproc_spm_utils.py`, can you put `ignore_exception=True` 

```
        stc_result = stc(in_files=sess_func, time_repetition=TR,
                         time_acquisition=TA, num_slices=nslices,
                         ref_slice=ref_slice + 1,
                         slice_order=list(slice_order + 1),  # SPM
                         ignore_exception=True
                         )
```

I think your example has crashed but, the exception has been caught; because, indeed, it should have done the co-registration, the motion correction, etc... Which he has not.

(Yes, indeed `disable_normalize = True`. But at least we should have a T1 re-align...)

**Comment by chrplr** [comment]
> (Yes, indeed disable_normalize = True. But at least we should have a T1 re-align...)

You mean a T2* (epi) realign?

**Comment by CherkaouiHamza** [comment]
No, I was thinking of the anatomical re-alignement: 

```
# Don't you want us to do coregistration of T1 (anat) and fMRI (func) ?
disable_coregister = False

# During coregistration, do you want us to register func -> anat or anat -> func ?
coreg_func_to_anat = True
```

Those enable the anatomical co-registration. 

But based on my z-map or your traceback, we seem to not do it.

(sorry if I use approximated vocabulary... :( )

**Comment by chrplr** [comment]
Ok, it is indeed just a vocabulary issue:

In SPM parlance:

* realignment (= movement detection and correction) only applies to EPIs  
* coregistration  applies to (mean) EPI and T1 (but does not involved normalzation)
* (spatial) normalization refers to the mapping to a normalized template.
