### ISSUE TITLE
'AxesSubplot' object has no attribute 'hold' on nipype_preproc_spm_multimodal_faces example

### ISSUE THREAD

**Issue by Hororohoruru** [neurospin/pypreprocess#313]
When trying to run the nipype_preproc_spm_multimodal_faces example, I get the following error:

```
Traceback (most recent call last):
  File "nipype_preproc_spm_multimodal_faces.py", line 51, in <module>
    segment=True, normalize=True)
  File "/home/juan/.local/lib/python3.7/site-packages/pypreprocess/nipype_preproc_spm_utils.py", line 1473, in do_subject_preproc
    subject_data.finalize_report(last_stage=last_stage)
  File "/home/juan/.local/lib/python3.7/site-packages/pypreprocess/subject_data.py", line 634, in finalize_report
    results_gallery=self.results_gallery)
  File "/home/juan/.local/lib/python3.7/site-packages/pypreprocess/reporting/preproc_reporter.py", line 737, in generate_tsdiffana_thumbnail
    axes = plot_tsdiffs(results, use_same_figure=False)
  File "/home/juan/.local/lib/python3.7/site-packages/pypreprocess/time_diff.py", line 233, in plot_tsdiffs
    ax.hold(True)
AttributeError: 'AxesSubplot' object has no attribute 'hold'
```

**Comment by Hororohoruru** [comment]
@bthirion

**Comment by KamalakerDadi** [comment]
Should be closed by this PR #311 

@Hororohoruru Could you please tell us if you don't see an error when you adapt the patch in PR #311 
Thanks

**Comment by thomasbazeille** [comment]
Can be closed thanks to #319
