### ISSUE TITLE
RuntimeError: List of functional images for session number 1 has the file bla.nii RuntimeError: List of functional images for session number 1 has the file 

### ISSUE THREAD

**Issue by dohmatob** [neurospin/pypreprocess#60]
Caused by pure python realign backend (realign_software=python option i .ini). Should be easy to reproduce.

```Memory]    0.0s, 0.0min: Loading pypreprocess.io_utils.niigz2nii from /neurospin/unicog/protocols/IRMf/Karla_Isa_Test_Analyse/results/al120399/cache_dir/joblib/pypreprocess/io_utils/niigz2nii/e956b6115c728ea4e9f2ca59a2c8fdcd
___________________________________________niigz2nii cache loaded - 0.0s, 0.0min
Traceback (most recent call last):
  File "/neurospin/unicog/resources/python_scripts/ManipKarla/1st_level_karla.py", line 240, in <module>
    subject_data = preproc(jobfile)
  File "/neurospin/unicog/resources/python_scripts/ManipKarla/1st_level_karla.py", line 39, in preproc
    subject_data = do_subjects_preproc(jobfile)[0]
  File "/volatile/depot_pypreprocess/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 1744, in do_subjects_preproc
    for subject_data in subjects]
  File "/volatile/depot_pypreprocess/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 1251, in do_subject_preproc
    software=coregister_software
  File "/volatile/depot_pypreprocess/pypreprocess/pypreprocess/nipype_preproc_spm_utils.py", line 388, in _do_subject_coregister
    subject_data.sanitize(niigz2nii=(software == "spm"))
  File "/volatile/depot_pypreprocess/pypreprocess/pypreprocess/subject_data.py", line 358, in sanitize
    self._check_func_names_and_shapes()
  File "/volatile/depot_pypreprocess/pypreprocess/pypreprocess/subject_data.py", line 246, in _check_func_names_and_shapes
    sess1 + 1, rep, count))
RuntimeError: List of functional images for session number 1 has the file /neurospin/unicog/protocols/IRMf/Karla_Isa_Test_Analyse/results/al120399/tmp/rAV1_1_al120399_20120829_acq1_06.nii repeated 144 times
````

**Comment by dohmatob** [comment]
Not applicable.
